@startuml
!theme toy
scale 1.5

title Передача данных по типу договору\nи окладу в сервис Займов

actor "Сотрудник займов" as sotrzaym 
participant "Сервис Займов" as szaym
participant "Сервис договоров" as sdogovor
participant "Сервис Кадры" as skadry

sotrzaym -> szaym: Запрашивает список\nдоговоров с типом\nтрудоустройства и зарплатой
activate szaym #FFBBBB

szaym -> sdogovor: Запрос типа договора\nGET/contarct_type/{employee_id}
activate sdogovor #FFBBBB
sdogovor --> szaym: Тип договора
deactivate sdogovor #FFBBBB

szaym -> skadry: Запрос заработной платы\nGET/sallary/{employee_id}
activate skadry #FFBBBB
skadry --> szaym: Заработная плата
deactivate skadry #FFBBBB

szaym --> sotrzaym: Показывает\nсписок договоров
deactivate szaym

@enduml
